PythonVersion="3.11.7"
pythonBuildCommandsFile="/tmp/zipdeploy/extracted/oryx-build-commands.txt"
packagedir=".python_packages/lib/site-packages"
OperationId="d7775778e1f022d4"
SourceDirectoryInBuildContainer="/tmp/zipdeploy/extracted"
PlatformName="python"
CompressDestinationDir="false"